name: Lint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: pip install .[cpu]
    - name: Run isort
      run: isort --check .
    - name: Run flake8
      run: flake8
    - name: Run black
      run: black . --check --verbose --diff
    - name: Run pylint
      run: pylint --persistent n --fail-under 10 -sn clashroyalebuildabot
    - name: Clean up build artifacts
      run: |
        rm -rf build
        rm -rf *.egg-info
        rm -rf dist
